" vim: set sw=2 ts=2 sts=2 et tw=120 foldmarker={,} foldlevel=10 foldmethod=marker:
"
" This is the personal .vimrc file of fishbupt
" Note: for fast startup time on windows platform,
" set PYTHON_HOST_PROG and PYTHON3_HOST_PROG environment variables

" 基础配置 {{{

if has('vim_starting')
  " 文件编码  
  setglobal fileencoding=utf-8
  set encoding=utf-8
  set fileencodings=usc-bom,utf-8,gbk,utf-16le,cp1252,iso-8859,cp936
  set fileformats=unix,mac,dos

  if &compatible
    " `:set nocp` has many side effects. Therefore this sould be done
    " only when 'compatible' is set.
    set nocompatible
  endif

endif

" This command has to be called after `set encoding`
scriptencoding utf-8

function! WIN()
  return has('win32') || has('win64')
endfunction

function! LINUX()
  return has('unix') && !has('macunix') && !has('win32unix')
endfunction

function! MAC()
  return has('macunix')
endfunction


if !WIN()
  set shell=/bin/sh
else
  set shell=cmd.exe
endif

" }}}

" 缩进. {{{
set autoindent          " Keep indentation
set tabstop=4           " Set tab equal to 4 spaces
set softtabstop=4       " Set soft tab equal to 4 spaces
set shiftwidth=4        " Set auto indent spacing
set expandtab           " Expand tab into spaces
set smarttab            " Insert spaces in front of lines
set backspace=indent,eol,start " Make backspace work like most other programs
set breakindent
set smartindent
" }}}

" 语法高亮. {{{
syntax on
filetype indent on
" }}}

" 外观显示. {{{
colorscheme desert
set ambiwidth=single " set to single if you really want to use powerline fonts
set cmdheight=1
set conceallevel=2
set cursorline       " highlight current line
set display=lastline
set laststatus=2     " display statusline
set showmode       " 在状态栏显示vim模式
if has('gui_running')
  if WIN()
    if exists(':simalt')
      autocmd GUIEnter * simalt ~x
    endif
  else
    set lines=100       " make vim take fullscreen by setting lines&columns
    set columns=500
  endif
endif
set list
set listchars=tab:>\ ,trail:\ ,extends:<,precedes:<
set noarabicshape
set nowrap
set number
set scrolloff=3
set showcmd
set showmatch
set signcolumn=auto    " Display sign only when there is one
set synmaxcol=512
set textwidth=120
" }}}

" GUI. {{{
if has('gui_running')
  set guifont=SauceCodePro_Nerd_Font_Mono:h11:cANSI:qDRAFT
endif
"}}}

" 备份. {{{
set backupdir=~/.vim/backup
set directory=~/.vim/swap
set nobackup
set noswapfile
set nowritebackup
" }}}

" History {{{
set history=2048
set undodir=~/.vim/undo
set undofile
set viewoptions=cursor,folds
" }}}

" Search. {{{
set hlsearch
set ignorecase
set incsearch
set smartcase
" }}}

" Others. {{{
set mouse=a                     " Automatically enable mouse usage.
set belloff=all
set completeopt=menu
set dictionary=/usr/share/dict/words
set diffopt+=iwhite
set formatoptions+=tjrol
set helplang=ja
set langnoremap
set lazyredraw
set matchpairs+=<:>
set regexpengine=2
set splitright
set updatetime=500
set virtualedit=block
set whichwrap=b,s,h,l,<,>,[,]
set wildignorecase
set wildmenu
" 手动配置状态栏 {{{
set statusline=%1*\%<%.50F\             "显示文件名和文件路径 (%<应该可以去掉)
set statusline+=%=%2*\%y%m%r%h%w\ %*        "显示文件类型及文件状态
set statusline+=%3*\%{&ff}\[%{&fenc}]\ %*   "显示文件编码类型
set statusline+=%4*\ row:%l/%L,col:%c\ %*   "显示光标所在行和列
set statusline+=%5*\%3p%%\%*            "显示光标前文本所占总文本的比例
 }}}
