" vim: set sw=2 ts=2 sts=2 et tw=120 foldmarker={,} foldlevel=10 foldmethod=marker:
"
" This is the personal .vimrc file of fishbupt
" Note: for fast startup time on windows platform,
" set PYTHON_HOST_PROG and PYTHON3_HOST_PROG environment variables

" Basic. {{{

if has('vim_starting')
  " Changing encoding in Vim at runtime is undefined behavior
  setglobal fileencoding=utf-8
  set encoding=utf-8
  set fileencodings=usc-bom,utf-8,gbk,utf-16le,cp1252,iso-8859,cp936
  set fileformats=unix,mac,dos

  if &compatible
    " `:set nocp` has many side effects. Therefore this sould be done
    " only when 'compatible' is set.
    set nocompatible
  endif

  " python host
  if !empty($PYTHON_HOST_PROG)
    let g:python_host_prog  = $PYTHON_HOST_PROG
  endif
  if !empty($PYTHON3_HOST_PROG)
    let g:python3_host_prog = $PYTHON3_HOST_PROG
  endif
endif

" This command has to be called after `set encoding`
scriptencoding utf-8

function! WIN()
  return has('win32') || has('win64')
endfunction

function! LINUX()
  return has('unix') && !has('macunix') && !has('win32unix')
endfunction

function! MAC()
  return has('macunix')
endfunction


if !WIN()
  set shell=/bin/sh
else
  set shell=cmd.exe
endif

" }}}

" Indent. {{{
set autoindent          " Keep indentation
set tabstop=4           " Set tab equal to 4 spaces
set softtabstop=4       " Set soft tab equal to 4 spaces
set shiftwidth=4        " Set auto indent spacing
set expandtab           " Expand tab into spaces
set smarttab            " Insert spaces in front of lines
set backspace=indent,eol,start " Make backspace work like most other programs
set breakindent
set smartindent
" }}}

" Appearance. {{{
set ambiwidth=single " set to single if you really want to use powerline fonts
set cmdheight=1
set conceallevel=2
set cursorline       " highlight current line
set display=lastline
set laststatus=2     " display statusline
set noshowmode       " don't display mode at statusline
if has('gui_running')
  set lines=100       " make vim take fullscreen by setting lines&columns
  set columns=500
endif
"set list
"set listchars=tab:>\ ,trail:\ ,extends:<,precedes:<
set noarabicshape
set nowrap
set number
" set relativenumber
set scrolloff=3
set showcmd
set showmatch
set signcolumn=auto    " Display sign only when there is one
set synmaxcol=512

" }}}

" Symbols define {{{
let s:powerline_font              = 1 " Enable for powerline glyphs
if s:powerline_font
  let g:symbol_separator_left     = "\uE0B0"
  let g:symbol_separator_right    = "\uE0B2"
  let g:symbol_subseparator_left  = "\uE0B1"
  let g:symbol_subseparator_right = "\uE0B3"
  let g:symbol_vcs_branch         = "\uE0A0"
else
  let g:symbol_separator_left     = "▏"
  let g:symbol_separator_right    = "▕"
  let g:symbol_subseparator_left  = "│"
  let g:symbol_subseparator_right = "│"
  let g:symbol_vcs_branch         = "\u16B4"
endif
" }}}

" Terminal UX {{{
set t_Co=256 " Terminal supports 256 colors
set t_md=    " Disable bold fonts in terminal

" Enable italics
let &t_ZH = "\e[3m"
let &t_ZR = "\e[23m"

if has('termguicolors')
  set termguicolors " Enable 24bit colors in terminal
endif
" }}}

" GUI. {{{
set showtabline=2 "Show tabline, enable lightline#tabline extentsion
if has('gui_running')
  let g:no_buffers_menu=1
  set guioptions+=M "Don't load menu.vim
  set guioptions-=m "Hide menu bar.
  set guioptions-=T "Hide toolbar.
  set guioptions-=L "Hide left-hand scrollbar
  set guioptions-=r "Hide right-hand scrollbar
  set guioptions-=b "Hide bottom scrollbar
  set guioptions-=e "Hide tab
  set mousehide     "Hide the mouse cursor while typing
  set visualbell
  set t_vb=
  " DON'T put quotes to font name
  set guifont=SauceCodePro_Nerd_Font_Mono:h11:cANSI:qDRAFT
endif
"}}}

" Folder. {{{
set foldenable
"set foldcolumn=1
"set foldmethod=indent
"set foldtext=Mopp_fold_text()
set foldmarker=\ {{{,\ }}}
" }}}

" Safety. {{{
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/swap
set swapfile
set writebackup
" }}}

" History {{{
set history=2048
set undodir=~/.vim/undo
set undofile
set viewoptions=cursor,folds
" }}}

" Search. {{{
set hlsearch
set ignorecase
set incsearch
set smartcase
" }}}

" Others. {{{
set mouse=a                     " Automatically enable mouse usage.
set belloff=all
set completeopt=menu
set dictionary=/usr/share/dict/words
set diffopt+=iwhite
set formatoptions+=tjrol
set helplang=ja
set langnoremap
set lazyredraw
set matchpairs+=<:>
set regexpengine=2
set splitright
set updatetime=500
set virtualedit=block
set whichwrap=b,s,h,l,<,>,[,]
set wildignorecase
set wildmenu

" Turn off default plugins. {{{
if !has('nvim')
  " vim8
  let g:plugin_bundle_dir = '~/vimfiles/'
else
  " neovim
  if WIN()
    let g:plugin_bundle_dir = '~/AppData/Local/nvim/'
  else
    let g:plugin_bundle_dir = '~/.config/nvim/'
  endif
endif
let g:loaded_2html_plugin = 1
let g:loaded_gzip = 1
let g:loaded_rrhelper = 1
let g:loaded_tar = 1
let g:loaded_tarPlugin = 1
let g:loaded_vimballPlugin = 1
let g:loaded_zip = 1
let g:loaded_zipPlugin = 1
let g:loaded_matchparen = 1
" }}}

" Configs for default scripts. {{{
let g:lisp_rainbow = 1
let g:lisp_instring = 1
let g:lispsyntax_clisp = 1
let g:c_syntax_for_h = 1
let g:tex_conceal = ''
let g:tex_flavor = 'latex'
" }}}
" }}}


" {{{ Load configs
let s:curdir = fnamemodify(resolve(expand('<sfile>:p')), ':h')

for fpath in sort(split(globpath(expand(s:curdir . '/config'), '*.vim'), '\n'))
  exe 'source' fpath
endfor
" }}}


